version: "3"
services:
  php:
    image: php:7.0
    entrypoint: ["php", "/var/www/public/index.php", "rabbitmq", "setup-fabric"]
    volumes:
      - ./:/var/www/
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"