version: "3"
services:
  php:
    build: docker/php
    entrypoint: ["php", "/var/www/public/index.php", "rabbitmq", "consumer", "rabbitmq_app_consumer"]
    volumes:
      - ./:/var/www/
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"